### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by TakodaNotDakota**
The previous license disallows any commerical use of unmodified versions, however it does not account for the modification size.

This new license allows commercial use, but requires _everyone_ to display a disclaimer on the game's title screen that the unmodified version can be played on our hosts.

It should be much more resistant to malicious actors.

### CODE REVIEW

**Comment by GiggyMantis** [comment]
I approve

**Comment by GiggyMantis** [comment]
> I think that the attribution should be required on their publishing page
> not in the game itself
> since we can just add that in to ours

**Comment by GiggyMantis** [comment]
@TakodaNotDakota

**Comment by TakodaNotDakota** [comment]
Okay dokey, @GiggyMantis. Please read the new commit I have made.

**Comment by GiggyMantis** [comment]
@kulupu-ko @rvtar34  review

**Comment by TakodaNotDakota** [comment]
@kulupu-ko @rvtar34 we need your official confirmation before continuing. Just go "yes" or react with a thumbs up and we can get this merged

**Comment by kulupu-ko** [comment]
yeah this is good

**Comment by rvtar34** [comment]
looks good

**Pull request merged**
